# Generated by Django 4.0.3 on 2023-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
