# Generated by Django 4.0.3 on 2023-01-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_saleslog_automobile_alter_saleslog_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_person', to='sales_rest.salesperson'),
        ),
    ]
